### ISSUE TITLE
Add the ability to create database transactions

### ISSUE THREAD

**Issue by lhofwimmer** [rpanic/ImposterDB#1]
Transactions are typically applied in databases to ensure an atomic transformation of data.
Similar to [JetBrains/Exposed](https://github.com/JetBrains/Exposed), ImpostedDB should only allow CRUD operations interacting with the database inside such constructs.

The tentative syntax looks as follows:
```
DB.tx {
    t.description = "20 Years"
    t.name = "New Tournament"
}
```

**Comment by rpanic** [comment]
Ideed, I already thought on something like that. That greatly increses the performance when dealing with large amounts of data. Also Error handling will be easy to do then

**Comment by rpanic** [comment]
Since the Connector Class to the "real" DB (Json-file) is a normal Imposer, we have two options on implementing Txs. We can implement them i a way, that the other Imposer Classes still get called, even though the data is not written yet. The other way would be to only call the Imposers on the Tx Commit
